spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payments?options=-c%20timezone=Asia/Kolkata
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: username
    password: password

server:
  port: 8083
